### ISSUE TITLE
Stemmer on Windows

### ISSUE THREAD

**Issue by MBristle** [eonum/medcodeassist#4]
The line  `require "lingua/#{RUBY_VERSION.sub(/\.\d+$/, '')}/stemmer_native"` which was commented   out  from the install.md instruction is needed in line   `stemmer = Lingua::Stemmer.new language: 'de'` in the method Token.find_token()

Uncommenting this line causes the following LoadError: `require': cannot load such file -- lingua/2.2/stemmer_native (LoadError)`.

- in fact: the specified folder/file doesn't exist
- creating the folder/file structure (creating the folder "2.2" and copying the file "stemmer_native.so" from folder "1.9" doesn't solve the problem. 
- editing the line to look for the file in folder "1.9" ( `require "lingua/1.9/stemmer_native"`) doesn't solve the problem either. 
- downgrading the version of RubyGems doesn't help.
- the problem occurs only on windows, not on linux

Is there any experience on that problem?

**Comment by asittampalam** [comment]
I haven't tested it in Windows yet but there is a section concerning Windows on https://github.com/aurelian/ruby-stemmer.
Try 
`gem install ruby-stemmer --platform=x86-mingw32`
or
`gem install ruby-stemmer --platform=x86-mswin32`

If that doesn't work I'll have a look at it next week.

**Comment by Arawan7** [comment]
Thanks for taking a look at it.
We already tried these ones without success..

**Comment by asittampalam** [comment]
Okay, I'll search for a solution next week. As the project mainly has to be deployable on a linux machine you might want to look into virtualization technologies (e.g. VirtualBox or something lightweight like Docker) for the time being.

**Comment by Arawan7** [comment]
That's good news. I'm using linux from the beginning on but not all of us..
Maybe, if all of us agreed to use linux and if it's ok for EONUM, we could ignore this problem and just work on linux? (To save time for you and us)

**Comment by asittampalam** [comment]
That'd be fine for us.

**Comment by MBristle** [comment]
Thank's for the feedback! Supported Development environment is now only Linux!
