### ISSUE TITLE
Code_proposals

### ISSUE THREAD

**Issue by Arawan7** [eonum/medcodeassist#8]
The post query
`HTTParty.post("http://[serverdomain]/api/v1/code_proposals", {query: {input_codes: ['ICD_E1141'], input_code_types: ['ICD'], get_icds: true, count: 1 }})`
which translates in
`http://[serverdomain]/api/v1/code_proposals?get_icds=true&count=1&input_codes[]=ICD_E1141&input_code_types[]=ICD`
returns an error: 
[code_proposals.html.zip](https://github.com/eonum/medcodeassist/files/211746/code_proposals.html.zip)

Should the input_codes and input_code_types arrays be 2d instead of a list?

**Comment by asittampalam** [comment]
It might be because I'm using hashes instead of arrays (Sorry, the documentation isn't clear on that as I just noticed). Try sending input_code_types and input_codes as hashes with shared keys for the moment. I might refactor that into using arrays later.
